# Site
name: 'UpNotes'
description: 'Learning never stops'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/upnotes'
ganalytics: 'G-Y699GMLWNL'
disqus: 'geekypandaml'
email: 'supernovaplazma@gmail.com'
mailchimp-list: 'https://geekypanda.us17.list-manage.com/subscribe/post?u=5de9558caf21ac2e9970bc459&amp;id=5a179d8608'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate-multiple
  
authors:
    sal:
      name:           Upendra
      site:           http://Upendra.ga
      avatar:         assets/images/avatar1.jpeg
      bio:            "Hi, I am Upendra, the author in Human and machine languages,I don't know to how 3 liner bio works so just Connect with me on social sites you will get to know me better."
      email:          supernovaplazma@gmail.com
      twitter:        https://twitter.com/bajpaiupendra
      fb:             https://www.facebook.com/upendra.bajpai.90
      ig:             https://www.instagram.com/upendrabajpai
      linkedIn:       https://in.linkedin.com/in/upendrabajpai
      medium:         https://medium.com/@supernovaplazma

    jane:
      name:           Shelly
      site:           https://www.upendra.ga
      avatar:         assets/images/avatar2.png
      bio:            "Blogger, techy, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-multiple
exclude:
  - Gemfile
  - Gemfile.lock

  
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

#multiple pagination
paginate_multiple:
  - paginate: 10
    paginate_path: '/langs/page:num/'
    sub_dir: '/Langs'

  - paginate: 10
    paginate_path: '/programming/page:num/'
    sub_dir: '/DSA'

  - paginate: 10
    paginate_path: '/android/page:num/'
    sub_dir: '/Android'

  - paginate: 10
    paginate_path: '/flutter/page:num/'
    sub_dir: '/Flutter'

  - paginate: 10
    paginate_path: '/system_design/page:num/'
    sub_dir: '/SD'

plugins_dir: ./_plugins

jekyll_get:
  - data: github
    json: 'https://api.github.com/users/upendra-bajpai/repos'
    cache: true
